# Generated by Django 6.0.1 on 2026-01-27 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the contact', max_length=50)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the contact (optional)', max_length=50)),
                ('phone', models.CharField(help_text='Primary phone number of the contact', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address of the contact (optional)', max_length=254)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the contact was created')),
                ('description', models.TextField(blank=True, help_text='Additional notes or description about the contact (optional)')),
            ],
        ),
    ]
