# Generated by Django 6.0.1 on 2026-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the contact (optional)', upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True, help_text='Whether to show the contact in the agenda'),
        ),
    ]
